# Generated by Django 2.1.11 on 2019-11-19 23:23

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# src.languages.migrations.0002_auto_20191119_2249

class Migration(migrations.Migration):

    replaces = [('languages', '0001_initial'), ('languages', '0002_auto_20191119_2249')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essential_price_per_word', models.DecimalField(decimal_places=2, max_digits=6)),
                ('professional_price_per_word', models.DecimalField(decimal_places=2, max_digits=6)),
                ('premium_price_per_word', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rush_price_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_language', to='languages.Language')),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_language', to='languages.Language')),
            ],
        ),
        migrations.RunPython(
            code=src.languages.migrations.0002_auto_20191119_2249.seed_languages,
        ),
    ]
