# Generated by Django 2.1.11 on 2019-11-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='quote_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='quotes.Quote'
            ),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
